Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.
1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

Llista de publicacions (/posts)
Llista d’usuaris (/users)
Llista de tasques (/todos)

In [3]:
import requests
import pandas as pd

URL = "https://jsonplaceholder.typicode.com"

In [9]:
link_posts = requests.get(URL + "/posts")   # Hacemos la petición a la API para obtener los posts

posts = link_posts.json() # Convertimos la respuesta a formato JSON para poder trabajar con ella

df_posts = pd.DataFrame(posts) 

df_posts.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [5]:
link_users = requests.get(URL + "/users")

users = link_users.json()

df_users = pd.DataFrame(users)

df_users.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [6]:
link_todos = requests.get(URL + "/todos")

todos = link_todos.json()

df_todos = pd.DataFrame(todos)

df_todos.head()

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

2. Mostra per pantalla:

La quantitat total de cada recurs.
El codi d'estat de cada petició.

In [7]:

print("POSTS")
print("Cantidad:", len(df_posts))
print("Status code:", link_posts.status_code)
print("-" * 30)

print("USERS")
print("Cantidad:", len(df_users))
print("Status code:", link_users.status_code)
print("-" * 30)

print("TODOS")
print("Cantidad:", len(df_todos))
print("Status code:", link_todos.status_code)

POSTS
Cantidad: 100
Status code: 200
------------------------------
USERS
Cantidad: 10
Status code: 200
------------------------------
TODOS
Cantidad: 200
Status code: 200

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [ ]:

# ID inexistente ej: 101 ya que hay solo 100 
response = requests.get(URL + "/users/101")


print("Status code:", response.status_code)

Status code: 404

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [10]:




# Datos de la nueva publicacion
new_post = {
    "title": "Analisis de datos",
    "body": "Este es un post de prueba para practicar requests en APIs",
    "userId": 1
}

# Peticion
response = requests.post(URL + "/posts", json=new_post)

# Mostrar resultados
print("Status code:", response.status_code)
print("Respuesta JSON:")
print(response.json())

Status code: 201
Respuesta JSON:
{'title': 'Analisis de datos', 'body': 'Este es un post de prueba para practicar requests en APIs', 'userId': 1, 'id': 101}

5. Fes una petició PATCH per modificar parcialment una publicació existent.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [11]:

#PUT reemplaza todo y PATCH solo el campo que se indique


# ID de publicación existente
post_id = 1

# Datos a modificar (solo un campo)
update_data = {
    "title": "Nuevo titulo actualizado ",
    "body": "Contenido actualizado del post"
}

# Petición PATCH
response = requests.patch(URL + f"/posts/{post_id}", json=update_data)

# Resultados
print("Status code:", response.status_code)
print("Respuesta JSON:")
print(response.json())

Status code: 200
Respuesta JSON:
{'userId': 1, 'id': 1, 'title': 'Nuevo titulo actualizado ', 'body': 'Contenido actualizado del post'}

6. Fes una petició DELETE sobre una publicació.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [12]:
#  DELETE
response = requests.delete(URL + f"/posts/{post_id}")

# Resultados
print("Status code:", response.status_code)
print("Respuesta JSON:")
print(response.json())

Status code: 200
Respuesta JSON:
{}

Nivell 2
Interacció amb una API pública real
1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

https://www.api-football.com/documentation-v3

2. Llegeix la documentació de l'API:

Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

In [30]:
import requests

url = "https://v3.football.api-sports.io/countries"

headers = {
    "x-apisports-key": "511021b484b52f1abe2bbda180f2a400"
}

response = requests.get(url, headers=headers)

print(response.status_code)
data = response.json()

import json
print(json.dumps(data, indent=2)[:1000])

200
{
  "get": "countries",
  "parameters": [],
  "errors": [],
  "results": 171,
  "paging": {
    "current": 1,
    "total": 1
  },
  "response": [
    {
      "name": "Albania",
      "code": "AL",
      "flag": "https://media.api-sports.io/flags/al.svg"
    },
    {
      "name": "Algeria",
      "code": "DZ",
      "flag": "https://media.api-sports.io/flags/dz.svg"
    },
    {
      "name": "Andorra",
      "code": "AD",
      "flag": "https://media.api-sports.io/flags/ad.svg"
    },
    {
      "name": "Angola",
      "code": "AO",
      "flag": "https://media.api-sports.io/flags/ao.svg"
    },
    {
      "name": "Antigua-And-Barbuda",
      "code": "AG",
      "flag": "https://media.api-sports.io/flags/ag.svg"
    },
    {
      "name": "Argentina",
      "code": "AR",
      "flag": "https://media.api-sports.io/flags/ar.svg"
    },
    {
      "name": "Armenia",
      "code": "AM",
      "flag": "https://media.api-sports.io/flags/am.svg"
    },
    {
      "name": "Aruba",
      "


3. Fes una petició GET senzilla:

Mostra el codi d'estat de la resposta.
Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [35]:
import requests

url = "https://v3.football.api-sports.io/teams"

headers = {
    "x-apisports-key": "511021b484b52f1abe2bbda180f2a400"
}

params = {
    "country": "Argentina"
}

response = requests.get(url, headers=headers, params=params)

print("Status code:", response.status_code)

data_futbol = response.json()

# VALIDACION
if len(data_futbol["response"]) > 0:
    print("Total equipos:", len(data_futbol["response"]))
    print("-" * 40)
    
    # Mostrar hasta 10 equipos
    for item in data_futbol["response"][:10]:
        team = item["team"]
        venue = item["venue"]
        
        # TEAM
        print("id:", team["id"])
        print("name:", team["name"])
        print("code:", team.get("code"))
        print("country:", team["country"])
        print("founded:", team["founded"])
        print("national:", team["national"])
        print("logo:", team["logo"])
        
        # VENUE
        print("stadium:", venue["name"])
        print("address:", venue["address"])
        print("city:", venue["city"])
        print("capacity:", venue["capacity"])
        print("surface:", venue["surface"])
        
        print("-" * 40)
else:
    print("No hay datos")

Status code: 200
Total equipos: 281
----------------------------------------
id: 26
name: Argentina
code: ARG
country: Argentina
founded: 1893
national: True
logo: https://media.api-sports.io/football/teams/26.png
stadium: Estadio Alberto José Armando
address: Brandsen 805, La Boca
city: Ciudad de Buenos Aires
capacity: 57200
surface: grass
----------------------------------------
id: 434
name: Gimnasia L.P.
code: GIM
country: Argentina
founded: 1887
national: False
logo: https://media.api-sports.io/football/teams/434.png
stadium: Estadio Juan Carmelo Zerillo
address: Avenida 60 y 118
city: La Plata, Provincia de Buenos Aires
capacity: 24544
surface: grass
----------------------------------------
id: 435
name: River Plate
code: RIV
country: Argentina
founded: 1901
national: False
logo: https://media.api-sports.io/football/teams/435.png
stadium: Estadio Mâs Monumental
address: Avenida Presidente José Figueroa Alcorta 7597, Núñez
city: Capital Federal, Ciudad de Buenos Aires
capacity: 83214
surface: grass
----------------------------------------
id: 436
name: Racing Club
code: RAC
country: Argentina
founded: 1903
national: False
logo: https://media.api-sports.io/football/teams/436.png
stadium: Estadio Presidente Juan Domingo Perón
address: Calle Mozart y Orestes Omar Corbatta
city: Avellaneda, Provincia de Buenos Aires
capacity: 51500
surface: grass
----------------------------------------
id: 437
name: Rosario Central
code: ROS
country: Argentina
founded: 1889
national: False
logo: https://media.api-sports.io/football/teams/437.png
stadium: Estadio Gigante de Arroyito
address: Avenida Génova y Avenida Centenario Rosario Central, Arroyito
city: Rosario, Provincia de Santa Fe
capacity: 41654
surface: grass
----------------------------------------
id: 438
name: Velez Sarsfield
code: VEL
country: Argentina
founded: 1910
national: False
logo: https://media.api-sports.io/football/teams/438.png
stadium: Estadio José Amalfitani
address: Avenida Juan B. Justo 9200, Liniers
city: Capital Federal, Ciudad de Buenos Aires
capacity: 49747
surface: grass
----------------------------------------
id: 439
name: Godoy Cruz
code: GOD
country: Argentina
founded: 1921
national: False
logo: https://media.api-sports.io/football/teams/439.png
stadium: Estadio Malvinas Argentinas
address: Calle San Francisco De Asis y Boulogne Sur Mer Mendoza
city: Mendoza, Provincia de Mendoza
capacity: 40268
surface: grass
----------------------------------------
id: 440
name: Belgrano Cordoba
code: BEL
country: Argentina
founded: 1905
national: False
logo: https://media.api-sports.io/football/teams/440.png
stadium: Estadio Julio César Villagra
address: Calle Dr. Arturo Orgaz 510 y La Rioja, Barrio Alberdi
city: Ciudad de Córdoba, Provincia de Córdoba
capacity: 28000
surface: grass
----------------------------------------
id: 441
name: Union Santa Fe
code: UNI
country: Argentina
founded: 1907
national: False
logo: https://media.api-sports.io/football/teams/441.png
stadium: Estadio 15 de Abril
address: Bulevar Pellegrini y Avenida Vicente López y Planes 3513
city: Ciudad de Santa Fe, Provincia de Santa Fe
capacity: 27000
surface: grass
----------------------------------------
id: 442
name: Defensa Y Justicia
code: DEF
country: Argentina
founded: 1935
national: False
logo: https://media.api-sports.io/football/teams/442.png
stadium: Estadio Norberto Tito Tomaghello
address: Avenida Humahuaca y Calle 611
city: Florencio Varela, Provincia de Buenos Aires
capacity: 20000
surface: grass
----------------------------------------

In [38]:
import pandas as pd

teams_list = []

for item in data_futbol["response"]:
    
    team = item["team"]
    venue = item["venue"]
    
    teams_list.append({
        "team_id": team["id"],
        "team_name": team["name"],
        "code": team["code"],
        "country": team["country"],
        "founded": team["founded"],
        "national": team["national"],
        "stadium": venue["name"],
        "address": venue["address"],
        "logo": team["logo"],
        "city": venue["city"],
        "capacity": venue["capacity"],
        "surface": venue["surface"]
    })

# Crear DataFrame
df_teams = pd.DataFrame(teams_list)

# Mostrar primeras filas
df_teams.to_csv("teams_argentina.csv", index=False) 

df_teams

,team_id,team_name,code,country,founded,national,stadium,address,logo,city,capacity,surface
0,26,Argentina,ARG,Argentina,1893.0,True,Estadio Alberto José Armando,"Brandsen 805, La Boca",https://media.api-sports.io/football/teams/26.png,Ciudad de Buenos Aires,57200.0,grass
1,434,Gimnasia L.P.,GIM,Argentina,1887.0,False,Estadio Juan Carmelo Zerillo,Avenida 60 y 118,https://media.api-sports.io/football/teams/434...,"La Plata, Provincia de Buenos Aires",24544.0,grass
2,435,River Plate,RIV,Argentina,1901.0,False,Estadio Mâs Monumental,"Avenida Presidente José Figueroa Alcorta 7597,...",https://media.api-sports.io/football/teams/435...,"Capital Federal, Ciudad de Buenos Aires",83214.0,grass
3,436,Racing Club,RAC,Argentina,1903.0,False,Estadio Presidente Juan Domingo Perón,Calle Mozart y Orestes Omar Corbatta,https://media.api-sports.io/football/teams/436...,"Avellaneda, Provincia de Buenos Aires",51500.0,grass
4,437,Rosario Central,ROS,Argentina,1889.0,False,Estadio Gigante de Arroyito,Avenida Génova y Avenida Centenario Rosario Ce...,https://media.api-sports.io/football/teams/437...,"Rosario, Provincia de Santa Fe",41654.0,grass
...,...,...,...,...,...,...,...,...,...,...,...,...
276,27413,Quilmes 2,NaN,Argentina,NaN,False,NaN,NaN,https://media.api-sports.io/football/teams/274...,NaN,NaN,NaN
277,27571,Atletico Escobar,NaN,Argentina,NaN,False,NaN,NaN,https://media.api-sports.io/football/teams/275...,NaN,NaN,NaN
278,27572,Defensores de Vilelas,NaN,Argentina,NaN,False,NaN,NaN,https://media.api-sports.io/football/teams/275...,NaN,NaN,NaN
279,27573,Tucuman Central,NaN,Argentina,NaN,False,NaN,NaN,https://media.api-sports.io/football/teams/275...,NaN,NaN,NaN
280,27574,Fundacion Amigos,NaN,Argentina,NaN,False,NaN,NaN,https://media.api-sports.io/football/teams/275...,NaN,NaN,NaN

Nivell 3
API d'Open Data Barcelona
1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [42]:
import requests


busca_placas = "plaques fotovoltaiques"

base = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"

search = requests.get(f"{base}/package_search?q={busca_placas}").json()

# Mostro el resultat amb el package_show, llista tots els títols inclosos
for busqueda in search["result"]["results"]:
    print("Nombre:", busqueda["title"])
    print("RESOURCE_ID:", busqueda["id"])
    print("-" * 50)

Nombre: Municipal photovoltaic panels in the city of Barcelona
RESOURCE_ID: 8b6fd878-f242-4e7f-b621-fa3ee605e8ca
--------------------------------------------------
Nombre: Types of municipal photovoltaic panels in the city of Barcelona
RESOURCE_ID: b29a6068-93f0-4593-9908-28415bf32190
--------------------------------------------------

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [45]:

dataset_placas = search["result"]["results"][0]    

for resource in dataset_placas["resources"]:
    print("Nombre:", resource["name"])
    print("Formato:", resource["format"])
    print("URL:", resource["url"])
    print("RESOURCE_ID:", resource["id"])
    print("-" * 50)

Nombre: 2025_Installacions_Fotovoltaiques_Municipals.csv
Formato: CSV
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/8b6fd878-f242-4e7f-b621-fa3ee605e8ca/resource/add38a29-8412-4bf2-b7f5-2a7514a9d380/download
RESOURCE_ID: add38a29-8412-4bf2-b7f5-2a7514a9d380
--------------------------------------------------
Nombre: 2022_Installacions_Fotovoltaiques_Municipals .csv
Formato: CSV
URL: https://opendata-ajuntament.barcelona.cat/data/dataset/8b6fd878-f242-4e7f-b621-fa3ee605e8ca/resource/eb63730f-fc70-4000-800a-97edb6675da8/download
RESOURCE_ID: eb63730f-fc70-4000-800a-97edb6675da8
--------------------------------------------------

3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [ ]:
resource_id = dataset_placas["resources"][0]["id"]

data_placas = requests.get(
    f"{base}/datastore_search?resource_id={resource_id}&limit=100"
).json()

4. Converteix els resultats a un DataFrame.

In [47]:
import pandas as pd
data_placas_df = pd.DataFrame(data_placas["result"]["records"])

data_placas_df

,Nom,Tipus_Equipament,Nombre_Llars_Subministrament,Energia_Produeix_ kWh,Nom_Districte,Emissions_ Estalviades_KgCO2,Longitude,Codi_Districte,Autoconsum_Xarxa,Potencia_kWp,Any_Alta,Latitude,_id,Adreca
0,Edifici Nou i Novíssim,Coberta,46,105800,Ciutat Vella,38088,2.177636994021850,1,Connexió a xarxa,84.64,2000,41.3817393706,1,"Plaça Sant Miquel, 1"
1,CEIP Costa i Llobera,Coberta,3,6000,Sarrià-Sant Gervasi,2160,2.108931198056360,5,Connexió a xarxa,4.8,2002,41.402116173325400,2,"Carrer de la Capella de Can Caralleu, 3"
2,CEIP Tàber,Coberta,16,37606,Sarrià-Sant Gervasi,13538,2.112299569219710,5,Connexió a xarxa,30.08,2002,41.401224466632500,3,"Carrer Esports, 9"
3,CEIP Font d'en Fargas,Coberta,3,6000,Horta-Guinardó,2160,2.165784055730250,7,Connexió a xarxa,4.8,2002,41.422796879358100,4,"Passeig Font d'en Fargues, 65"
4,Pèrgola de Vallbona,Espai públic,38,86400,Nou Barris,31104,2.186297977432090,8,Connexió a xarxa,86.4,2002,41.465160742776000,5,Carrer Castelladral 6-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Casal de barri Trinitat Nova,Coberta,5,11238,Nou Barris,4046,2.187457330231,8,Autoconsum,8.99,2018,41.452673423135,96,"C. de Garbí, 3"
96,Pèrgola Parc Josep Maria Serra Martí,Espai públic,13,29700,Nou Barris,10692,2.166947510231,8,Autoconsum,29.7,2018,41.442153117039,97,Parc de Serra i Martí
97,Biblioteca Trinitat Vella-José Barbero,Coberta,8,18900,Sant Andreu,6804,2.190725181778,9,Autoconsum,15.12,2018,41.449251180315,98,"Carrer de Galícia, 16"
98,Centre Cívic Trinitat Vella,Coberta,15,35200,Sant Andreu,12672,2.191214255731,9,Connexió a xarxa,28.16,2012,41.451768366126,99,"Carrer Foradada, 36"
99,Cal l'Alier,Coberta,37,85463,Sant Martí,30767,2.203817811547,10,Autoconsum,68.37,2018,41.410141376588,100,"Carrer de Fluvià, 120X"

5. Desa el DataFrame en un fitxer .csv.

In [48]:
data_placas_df.to_csv("placasfotovoltaiquesbarcelona.csv", index=False)